### ISSUE TITLE
$insightsResponse->riskScore   returns    12,6  instead of 12.6 

### ISSUE THREAD

**Issue by wnedoe** [maxmind/minfraud-api-php#110]
It seems that on certain international locale settings  (german) 
the riskscore is returned as    xx,yy  instead of xx.yy    and is so creating problems. 

in the same script just one line later (so same language/locale settings)  I  echoed  5/2  and got 2.5 (!! with the decimal dot) 

php 7.4.15
centos 7 
installed with composer  latest update

**Comment by oschwald** [comment]
How are you displaying the risk score? The number is returned as a floating point number, not a string. The API has no control over how PHP displays it.

**Comment by wnedoe** [comment]
I did nothing with it. 

My debug & workaround is now:  

    $risk = $insightsResponse->riskScore; //das ist der zentrale Wert der Risikobewertung
    $log->info( $risk);     13,2 
    $risk = (float)str_replace(',', '.', $risk);
    $log->info( $risk);    13.2

**Comment by oschwald** [comment]
Can you log `gettype($risk)` to confirm it is a double?

**Comment by wnedoe** [comment]
89,49 type: double
89.49 - type: string

As soon as i cast it back to double it will get 89,49  :-(  so currently my only chance is to  insert it as string into the double field of the db  :-/  

But 5/2 is displayed as 2.5 (!!!)  


Very strange

**Comment by oschwald** [comment]
From the [PHP docs](https://www.php.net/manual/en/language.types.string.php#language.types.string.casting:~:text=As%20of%20PHP%208.0.0%2C%20the%20decimal,(category%20LC_NUMERIC).%20See%20the%20setlocale()%20function.):

> As of PHP 8.0.0, the decimal point character is always .. Prior to PHP 8.0.0, the decimal point character is defined in the script's locale (category LC_NUMERIC). See the setlocale() function.

I am not sure why 5/2 ends up as 2.5 though. Are you displaying it in exactly the same way?

**Comment by oschwald** [comment]
I am going to close this as I believe it to be the behavior of PHP version before 8.0 and outside of our control. Please let me know if you discover otherwise.
