### ISSUE TITLE
Deprecation notices appeared after switch to php 8.2 from php 7.4

### ISSUE THREAD

**Issue by alebedev80** [maxmind/minfraud-api-php#145]
After switching to PHP 8.2 from PHP 7.4 in a log file appeared follow notices:

PHP Deprecated:  Creation of dynamic property MaxMind\MinFraud\Model\Disposition::$rawResponse is deprecated in /var/www/vhosts/httpdocs/vendor/maxmind/minfraud/src/MinFraud/Model/AbstractModel.php on line 24
PHP Deprecated:  Creation of dynamic property MaxMind\MinFraud\Model\ScoreIpAddress::$rawResponse is deprecated in /var/www/vhost/httpdocs/vendor/maxmind/minfraud/src/MinFraud/Model/AbstractModel.php on line 24

**Comment by oschwald** [comment]
Thanks! 1.23.0 was release with a fix for this.
