### ISSUE TITLE
Extracting user_agent from $values should not depend on $sessionId

### ISSUE THREAD

**Issue by gkuhlmann** [maxmind/minfraud-api-php#172]
We encountered this behavior after upgrading from MinFraud 1.x to 3.x

IMO the `user_agent` value should be extracted/removed from the `$values` array regardless of whether a session_id exists.

see https://github.com/maxmind/minfraud-api-php/blob/3ad51f54ac26aa5fd7b45a8e52bc2830032f2351/src/MinFraud.php#L216-L218

**Comment by oschwald** [comment]
Thank you. That is certainly a bug. I am not sure what the intent was there.
