### ISSUE TITLE
ca cert - SSL: certificate verification failed 

### ISSUE THREAD

**Issue by pascal-larocque** [maxmind/minfraud-api-php#19]
OpenSSL 1.0.2h  3 May 2016
OS X 10.11.5
PHP 5.6.16
curl 7.43.0 (x86_64-apple-darwin15.0) libcurl/7.43.0 SecureTransport zlib/1.2.5

The ca.pem included in the Client is generating an SSL verification error.  Disabling the cacert curl opt works but there is no way of doing this without forking the project. Any ideas?

**Comment by oschwald** [comment]
What version of `maxmind/web-service-common-php` are you using? The latest version uses `composer/ca-bundle` rather than our own cert bundle, which should fix the issue for most users.

**Comment by pascal-larocque** [comment]
V0.6.1
looking at the composer.json, it still uses web-server-common 0.2.0. It looks like composer/ca-bundle it only in version 0.3.0.

**Comment by pascal-larocque** [comment]
Tried forking the project to set web-service-common to v0.3.0 which is using ca-bundle but it still gives SSL verification error with version 0.3.0. Why are you forcing --cacert flag in curl? Removing this the flag works and the certificate is verified also.

**Comment by oschwald** [comment]
We are providing a cert bundle as we cannot rely on a system bundle being available on all platforms. Guzzle and Composer do the same thing. I am surprised `composer/ca-bundle` is not working for you given that it should use the system cert if available.

**Comment by oschwald** [comment]
You can always explicitly pass whatever bundle you want using the `caBundle` option.

**Comment by oschwald** [comment]
Although it sounds like it won't work for you, I did a new release with the new `composer/ca-bundle` dependency.

I'd be curious which bundle `composer/ca-bundle` is returning and how that differs from whatever your version of curl is using by default.

**Comment by pascal-larocque** [comment]
testing on a centos version 6.7 does work it's using bundle /etc/pki/tls/certs/ca-bundle.crt on the OS X machine it's using /usr/local/etc/openssl/cert.pem by default. Since OS X curl uses the keychain by default, we should have the option to disable using cabundle by passing FALSE for example.

**Comment by oschwald** [comment]
Could you confirm that `maxmind/web-service-common:dev-greg/osx-securetransport-fix` works without having to specifically pass a `caBundle` value?

**Comment by pascal-larocque** [comment]
CONFIRMED!!!

it worked on Mac OS and Centos.
If you could let me know when the new version of maxmind/minfraud using the fixed version of web-service-common is up on packagist that would be great.

Thanks
