### ISSUE TITLE
Have a cleaner documentation about client's optional parameters (connectTimeout for example)

### ISSUE THREAD

**Issue by ahfeel** [maxmind/minfraud-api-php#20]
Hi,

Maxmind servers were down for a while tonight, pointing to us that the connection timeout of the underlying http request is quite long, hence generating delays to our users in this particular downtime case.

I had to dig into the code of the webservice-common repository to find about connectTimeout. Would be great to have that documented somewhere here :-)

**Comment by autarch** [comment]
Hi @ahfeel, I don't think we were aware of any outages yesterday. If you have any more specifics please let us know here or email support@maxmind.com

I'll add the documentation idea to our internal todo list, but sometimes these things take a while to schedule, so a doc patch would be very welcome.

**Comment by autarch** [comment]
Actually, I talked to someone on our sysadmin team and he told me there _was_ a small outage affecting our London data center. I'm assuming since you're in Spain you might be using that one directly.

**Comment by oschwald** [comment]
We added a [note directing people to the API documentation to the README.md](https://github.com/maxmind/minfraud-api-php#api-documentation). We may also add examples of how to use some of the options in the future.
