### ISSUE TITLE
Can't bypass validation

### ISSUE THREAD

**Issue by dxrrxns** [maxmind/minfraud-api-php#25]
I could be doing this incorrectly so I apologize if I am in error... 
I am trying to turn off the validation and just return a default score if nothing is returned so that it does not stop my process.

`$mf = new MinFraud(1,'xxx',['validateInput' => false]);`

above is how i tried to set the options... I still get a private ip address error in dev ...

**Comment by oschwald** [comment]
Even if you turn off validation in the client API, the web service itself requires a public IP address. It will return an error on a private one.
