### ISSUE TITLE
PermissionRequiredException

### ISSUE THREAD

**Issue by sdtorresl** [maxmind/minfraud-api-php#30]
I'm using the demo published in https://packagist.org/packages/maxmind/minfraud in order to test minfraud service and I have the follow exception:

[Fri Dec 02 22:43:51.073898 2016] [:error] [pid 25934] [client 186.154.86.68:50646] PHP Fatal error:  Uncaught MaxMind\\Exception\\PermissionRequiredException: You do not have permission to use this service interface in /var/www/public/demoetb/webtv/vendor/maxmind/web-service-common/src/WebService/Client.php:339\nStack trace:\n#0 /var/www/public/demoetb/webtv/vendor/maxmind/web-service-common/src/WebService/Client.php(290): MaxMind\\WebService\\Client->handleWebServiceError('You do not have...', 'PERMISSION_REQU...', 403, '/minfraud/v2.0/...')\n#1 /var/www/public/demoetb/webtv/vendor/maxmind/web-service-common/src/WebService/Client.php(194): MaxMind\\WebService\\Client->handle4xx(403, 'application/vnd...', '{"code":"PERMIS...', 'Factors', '/minfraud/v2.0/...')\n#2 /var/www/public/demoetb/webtv/vendor/maxmind/web-service-common/src/WebService/Client.php(116): MaxMind\\WebService\\Client->handleResponse(403, 'application/vnd...', '{"code":"PERMIS...', 'Factors', '/minfraud/v2.0/...')\n#3 /var/www/public/demoetb/webtv/vendor/maxmind/minfraud/src/MinFraud.php(345): MaxMind\\WebService\\Client->post('Factors', '/minfraud/v2.0/.. in /var/www/public/demoetb/webtv/vendor/maxmind/web-service-common/src/WebService/Client.php on line 339

User and license are corrects. I have already tested the service with java and the firewall is open. I'm using PHP 7.

**Comment by oschwald** [comment]
You will need to contact support@maxmind.com as your account does not have the requisite permissions.
