### ISSUE TITLE
Docs are more explicit about request object immutability (was: Unusual implementation of fluent interface breaks expected behavior)

### ISSUE THREAD

**Issue by erangalp** [maxmind/minfraud-api-php#35]
The Minfraud class uses a fluent interface in which an object is returned from most methods, so you could chain method calls one after the other as is shown in the usage example.

Normally, an implementation of this in PHP would return the calling object ($this), but in this implementation a new object is cloned from the original and returned instead.

This causes unexpected behavior to happen if you do happen to have breaks in method calls, which is very common when working with real data that needs to be massaged into what Minfraud expects. For example, when I do this:

               $mf = new MinFraud($this -> _userID, $this -> _key);
               $request = $mf->withDevice([
			'ip_address' => $ip,
			'user_agent' => $_SERVER['HTTP_USER_AGENT'],
			'accept_language' => $_SERVER['HTTP_ACCEPT_LANGUAGE']
		]);
		

		$parts = explode(' ',$data['name']);
		$addressFields = [
			'first_name'         => $parts[0],
			'last_name'          => $parts[1],
			'address'            => $data['address_street'],
			'address_2'          => $data['address_street2'],
			'city'               => $data['address_city'],
			'country'            => $data['address_country'],
			'postal'             => $data['address_zip'],
			'phone_number'       => $data['phone'],
		];
		if(isset($data['address_state'])) {
			$addressFields['region'] = $data['address_state'];
		}
		$request ->withBilling($addressFields);

The `withBilling()` call doesn't actually modify the original $request object I created initially. I would have to reassign it every time I call a method that adds data to the minfraud request object. 

I fixed this by removing the cloning of the request object in the `validateAndAdd()` and `withShoppingCartItem()` and instead operating on the $this scope and returning it, but it would be best if that's how the official library behaved as well.

**Comment by oschwald** [comment]
Immutable objects are an intentional design decision that is well within PHP norms. This is the same behavior as PSR-7 HTTP messages, for instance.

**Comment by erangalp** [comment]
It would be useful to mention that this is the case in the documentation. Only by going over the Minfraud transaction logs did we realize that was the case.

**Comment by oschwald** [comment]
The docs do say, "Each method call returns a new object," but there are probably ways we could make it more explicit.

**Comment by erangalp** [comment]
You are right, we must have missed that! Probably putting that as a comment in the usage example would help reduce confusion. Or showing an example where the calls are separated.
