### ISSUE TITLE
Connection is not re-used

### ISSUE THREAD

**Issue by willemstuursma** [maxmind/minfraud-api-php#59]
Good morning,

We are using a daemon to execute API calls to to MinFraud. To reduce overhead, we would like the TCP connection to be re-used between API calls. 

Would you accept a pull request that will change the `\MaxMind\WebService\Http\CurlRequest` class to add a private static to keep the cURL resource between requests. 

The PR would also bump the minimum PHP version to 5.5 because it will require the `curl_reset` function to be used.

**Comment by oschwald** [comment]
@willemstuursma, are you still interested in making a PR for this?

**Comment by willemstuursma** [comment]
Yes, I created https://github.com/maxmind/web-service-common-php/pull/24.
