### ISSUE TITLE
php 7 Fatal error

### ISSUE THREAD

**Issue by pawaroti** [maxmind/minfraud-api-php#6]
As PHP 7 was released I tried launching a project that includes maxmind/minfraud, however the thrown expection is as it follows:

Fatal error: Cannot use 'String' as class name as it is reserved in vendor/respect/validation/library/Rules/String.php on line 4

minfraud depends on respect/validation which already fix this. Maybe some update?

**Comment by oschwald** [comment]
Thanks for the report. This is on our radar and we hope to fix it within the next week or so.
