### ISSUE TITLE
Validation Issue with Order and Shopping Cart Item Amount

### ISSUE THREAD

**Issue by Sn0wCrack** [maxmind/minfraud-api-php#78]
According to the minFraud API documentation the Order and Shopping Cart endpoints both state "The value must be at least 0 and at most 1e14 – 1."

However it appears this library validates for at least 1 due to the following line:

```php
v::key('amount', v::floatVal()->min(0, false), false),
```

Which validates from a minimum of 0 non-inclusive.

Just to clarify, is the documentation correct in stating that a 0 amount is acceptable to send through to the API?

**Comment by oschwald** [comment]
Thanks for reporting this. The documentation is correct that 0 is acceptable. I have fixed the API in https://github.com/maxmind/minfraud-api-php/pull/80.

**Comment by Sn0wCrack** [comment]
Thanks a lot of fixing that, is there any ETA on this getting into a new package version?

**Comment by oschwald** [comment]
We just did a release. Thanks!
