### ISSUE TITLE
no way to reset state between calls

### ISSUE THREAD

**Issue by Gamesh** [maxmind/minfraud-api-php#79]
Hi, 

MinFraud class is stateful as information is not reset/cleaned between requests, which will cause an unexpected behavior if you do batch calling.
For example constructing request conditionally: omitting or adding data to the request populates the internal $content field. Once` insights()` or` score()` is called the internal content of the field is not cleared, but the data is not needed anymore. 
So data persists between calls and can bleed from one request to the other if not overriden by appropriate `with*()` call before next call to `score()`.

would be good to have a method to reset state between calls

**Comment by oschwald** [comment]
The objects are intentionally immutable. A reset method would be contrary to that. The `with*()` calls do not change the underlying object but create a new one. As such, if you want to reuse the object created by the constructor, i.e., when you call `new MinFraud(...)` between calls, you can. You just need to save it to a different variable.

**Comment by Gamesh** [comment]
@oschwald yeah, i know, but that does not work in most modern frameworks that use dependency injection. Also if i'm creating an instance of MinFraud that leaves my service untestable as it no longer uses DI and that dependency can't be mocked. We then have to resort to hacks like setters that replace dependencies when testing.
I would argue that both cons outweigh the pros.

**Comment by oschwald** [comment]
I am a bit confused. Why can't you inject the object created by `new MinFraud(...)`? It is immutable and can be reused multiple times.

**Comment by Gamesh** [comment]
never mind, didn't notice that it was $new->content that is being written to, miss-took it for $this->content as it was private
