### ISSUE TITLE
Type errors on reportTransaction

### ISSUE THREAD

**Issue by dmitrymalashko** [maxmind/minfraud-api-php#99]
Error message:
**Argument 2 passed to MaxMind\WebService\Client::handleResponse() must be of the type string or null, boolean given, called**

Installed latest minfraud (v1.16), web-service-commin (v0.8.0)
![minfraud](https://user-images.githubusercontent.com/9327377/97842579-dff87000-1cf8-11eb-8e14-09f0e73d9431.png)

**Comment by oschwald** [comment]
Thanks for reporting this! It has been fixed in 1.16.1.
